steps:
  - label: run bats tests
    plugins:
      - docker-compose#v4.5.0:
          run: tests

  - label: run shellcheck
    plugins:
      - shellcheck#${BUILDKITE_COMMIT}:
          files:
            - hooks/*
            - buildkite/*.sh

  steps:
  - label: ":eslint:"
    command: "npm run lint"
    plugins:
      - docker-compose#v3.10.0:
          run: linter
